source "https://rubygems.org"

gem "rake"

gem "motion-support", ">= 0.2.2"

# Beyond cocoapods 0.16.4 requires motion-cocoapods 1.3.0.rc1 unlreleased as of 2013-05-03
# TODO update when motion-cocoapods 1.3 is released
#gem 'cocoapods', '~>0.19.1'
#gem 'motion-cocoapods', '1.3.0.rc1'

gem 'cocoapods', '~>0.16.4'
gem 'motion-cocoapods', '1.2.1'
