# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'rubygems'
require 'motion-cocoapods'

# Note: BubbleWrap really shouldn't be a dependency.
# However NSDate.dateWithNaturalLanguageString in model_casts.rb are apparently defined/included by it somewhere,
#  and replacing them with NSDateFormatter seemed to break other specs. Leave it alone for now...
require 'bubble-wrap'

$: << File.expand_path('../../lib', __FILE__)
require 'motion_model'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'sqlite3_sample_app'
  app.pods do
    # Note: v2.0 podspec is not up to date with master branch at https://github.com/ccgus/fmdb
    # For now, do "git submodule --update -init" to get a local install
    #pod 'FMDB'
    pod 'FMDB', local: File.expand_path('../../vendor/fmdb', __FILE__)
  end
end
