# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
require 'rubygems'
require 'bundler'
Bundler.require

require 'motion-cocoapods'

$: << File.expand_path('../../lib', __FILE__)
require 'motion_model'
require 'motion_model/sql'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'sqlite3_sample_app'
  app.detect_dependencies = false
  app.pods do
    pod 'FMDB', '2.1'
  end 
end
